local theme = {
	TextColor = Color3.fromRGB(237, 222, 231),

	Background = Color3.fromRGB(18, 16, 15),
	Topbar = Color3.fromRGB(2, 2, 2),
	Shadow = Color3.fromRGB(40, 40, 40),

	NotificationBackground = Color3.fromRGB(20, 20, 20),
	NotificationActionsBackground = Color3.fromRGB(230, 230, 230),

	TabBackground = Color3.fromRGB(18, 16, 15),
	TabStroke = Color3.fromRGB(18, 16, 15),
	TabBackgroundSelected = Color3.fromRGB(110, 50, 210),
	TabTextColor = Color3.fromRGB(237, 222, 231),
	SelectedTabTextColor = Color3.fromRGB(237, 222, 231),

	ElementBackground = Color3.fromRGB(21, 19, 18),
	ElementBackgroundHover = Color3.fromRGB(25, 23, 22),
	SecondaryElementBackground = Color3.fromRGB(22, 20, 19),
	ElementStroke = Color3.fromRGB(18, 16, 15),
	SecondaryElementStroke = Color3.fromRGB(18, 16, 15),

	SliderBackground = Color3.fromRGB(2, 2, 2),
	SliderProgress = Color3.fromRGB(110, 50, 210),
	SliderStroke = Color3.fromRGB(18, 16, 15),

	ToggleBackground = Color3.fromRGB(36, 10, 60),
	ToggleEnabled = Color3.fromRGB(110, 50, 210),
	ToggleDisabled = Color3.fromRGB(2, 2, 2),
	ToggleEnabledStroke = Color3.fromRGB(110, 50, 210),
	ToggleDisabledStroke = Color3.fromRGB(2, 2, 2),
	ToggleEnabledOuterStroke = Color3.fromRGB(18, 16, 15),
	ToggleDisabledOuterStroke = Color3.fromRGB(18, 16, 15),

	DropdownSelected = Color3.fromRGB(110, 50, 210),
	DropdownUnselected = Color3.fromRGB(25, 23, 22),

	InputBackground = Color3.fromRGB(36, 10, 60),
	InputStroke = Color3.fromRGB(18, 16, 15),
	PlaceholderColor = Color3.fromRGB(237, 222, 231)
}