local theme = {
	TextColor = Color3.fromRGB(237, 222, 231),

	Background = Color3.fromRGB(18, 16, 15),
	Topbar = Color3.fromRGB(2, 2, 2),
	Shadow = Color3.fromRGB(40, 40, 40),

	NotificationBackground = Color3.fromRGB(2, 2, 2),
	NotificationActionsBackground = Color3.fromRGB(230, 230, 230),

	TabBackground = Color3.fromRGB(18, 16, 15),
	TabStroke = Color3.fromRGB(18, 16, 15),
	TabBackgroundSelected = Color3.fromRGB(110, 50, 210),
	TabTextColor = Color3.fromRGB(237, 222, 231),
	SelectedTabTextColor = Color3.fromRGB(131, 59, 255),

	--ElementBackground = Color3.fromRGB(21, 19, 18),
	ElementBackground = Color3.fromRGB(26, 25, 24),
	ElementBackgroundHover = Color3.fromRGB(21, 20, 20),
	SecondaryElementBackground = Color3.fromRGB(26, 25, 24),
	ElementStroke = Color3.fromRGB(18, 16, 15),
	SecondaryElementStroke = Color3.fromRGB(18, 16, 15),

	SliderBackground = Color3.fromRGB(2, 2, 2),
	SliderProgress = Color3.fromRGB(110, 50, 210),
	SliderStroke = Color3.fromRGB(18, 16, 15),

	ToggleBackground = Color3.fromRGB(36, 10, 60),
	ToggleEnabledBackground = Color3.fromRGB(110, 50, 210),
	ToggleEnabled = Color3.fromRGB(2, 2, 2),
	ToggleDisabled = Color3.fromRGB(2, 2, 2),
	ToggleEnabledStroke = Color3.fromRGB(110, 50, 210),
	ToggleDisabledStroke = Color3.fromRGB(2, 2, 2),
	ToggleEnabledOuterStroke = Color3.fromRGB(18, 16, 15),
	ToggleDisabledOuterStroke = Color3.fromRGB(18, 16, 15),
	
	--DropdownBackgroundColor = Color3.fromRGB(10, 10, 10),
	DropdownBackgroundColor = Color3.fromRGB(26, 25, 24),
	DropdownBackgroundHoverColor = Color3.fromRGB(21, 20, 20),
	DropdownOpenBackgroundColor = Color3.fromRGB(26, 25, 24), --> 36, 10, 60
	DropdownItemBackground = Color3.fromRGB(17, 15, 14),
	DropdownSecondaryColor = Color3.fromRGB(131, 59, 255),
	DropdownItemSelected = Color3.fromRGB(110, 50, 210),
	DropdownItemUnselected = Color3.fromRGB(2, 2, 2),

	InputBackground = Color3.fromRGB(10, 10, 10),
	InputFocusedBackground = Color3.fromRGB(36, 10, 60),
	PlaceholderColor = Color3.fromRGB(237, 222, 231)
}